apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connector
  labels:
    app: neo4j-connector
spec:
  selector:
    matchLabels:
      app: neo4j-connector
  template:
    metadata:
      labels:
        app: neo4j-connector
    spec:
      containers:
        - name: neo4j-connect
          image: veedata/kafka-neo4j-connect
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-neo4j-connector-svc
spec:
  selector:
    app: neo4j-connector
  ports:
  - protocol: TCP
    name: rest
    port: 8083
    targetPort: 8083
